name: Java CI

on:
  workflow_call:
    inputs:
      run_tests:
          required: true
          type: boolean
      run_lint:
          required: true
          type: boolean
  workflow_dispatch:
    inputs:
      run_tests:
          description: 'Deseja executar testes?'
          required: true
          default: 'true'
          type: boolean
      run_lint:
          description: 'Deseja executar lint?'
          required: true
          default: 'true'
          type: boolean

jobs:
  checkout:
    name: Checkout 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  build:
    name: Build 
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build com Maven
        working-directory: devcalc 
        run: mvn clean install -DskipTests

  lint-and-test:
    needs: [checkout, build]
    uses: jvcmtr/Devops_DR5_TP1/.github/workflows/lint-and-test.yaml@main
    with:
      run_tests: ${{ inputs.run_tests }}
      run_lint: ${{ inputs.run_lint }}
    
  package:
    name: Compile
    runs-on: ubuntu-latest
    needs: [lint-and-test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gerar pacote JAR
        working-directory: devcalc 
        run: mvn package

  connect_to_db:
    needs: [checkout]
    uses: jvcmtr/Devops_DR5_TP1/.github/workflows/connect.yaml@main
    with:
      connection_string: ${{vars.DB_CONNECTION}}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [package, lint-and-test, connect]
    steps:
      - name: Simula deploy
        run: echo "Deploy realizado com sucesso"

      - name: Simula deploy
        run: echo "Deploy realizado com sucesso"


