name: Connect

on:
  workflow_call:
    secrets:
      connection_string:
          required: true
  

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Connection
        run: echo secrets.connection_string 

    steps:
      - name: Fail connection
        if: ${{ secrets.connection_string == '' }}
        run: echo "Fail to connect to the server"

      - name: Succeed Connection
        if: ${{ secrets.connection_string != '' }}
        run: echo "successfully connected to the server"