name: Connect

on:
  workflow_call:
    secrets:
      connection_string:
          required: true
  

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: validate_secret
        run: |
          if [ -z "${{ secrets.connection_string }}" ]; then
            exit 1
          else
            echo "successfully connected to the server"
          fi