name: Lint and Test

permissions:
  issues: write

on:
  workflow_call:
    inputs:
      run_tests:
          required: true
          type: boolean
      run_lint:
          required: true
          type: boolean

jobs:
  # Tirado diretamente da documentação oficial ( https://github.com/marketplace/actions/run-java-checkstyle#example-usage ) 
  checkstyle_job:
    if: ${{ inputs.run_lint }} 
    runs-on: ubuntu-latest
    name: Checkstyle job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'

  test:
    name: Test
    if: ${{ inputs.run_tests }} 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Executar testes com Maven
        id: test-result
        working-directory: devcalc 
        run: mvn test
        continue-on-error: true
      
      - name: Criar issue
        if: steps.test-result.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.create({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  title: "Falha no teste",
                  body: `Resultado do teste: https://github.com/jvcmtr/Devops_DR5_TP1/actions/runs/${{ github.run_id }}`
                });