name: main_trigger

# Este arquivo tem como objetivo mapear os gatilhos
# e passar os argumentos default para CI, diferenciando
# o dispatch manual do uso dos gatilhos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
        - 'devcalc/src/**'

jobs:
  CI:
    uses: jvcmtr/Devops_DR5_TP1/.github/workflows/ci.yaml@main
    with:
      run_tests: ${{vars.USE_TEST_ON_TRIGGER}}
      run_lint: ${{vars.USE_LINT_ON_TRIGGER}}