name: triggers

# Este arquivo tem como objetivo setar os valores default para CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
        - 'devcalc/src/**'

jobs:
  CI:
    uses: jvcmtr/Devops_DR5_TP1/.github/workflows/ci.yaml@main
    with:
      run_tests: true
      run_lint: true